version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
os: Visual Studio 2015
configuration: Release
platform:
- x86
- x64
- ARM
install:
- ps: >-
    $msiPath = "$($env:USERPROFILE)\MultilingualAppToolkit.msi"

    (New-Object Net.WebClient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/6dab9154-a7e1-46e4-bbfa-18b5e81df520/file/143697/16/MultilingualAppToolkit.msi', $msiPath)

    cmd /c start /wait msiexec /i $msiPath /q
before_build:
- cmd: nuget restore OpenHAB.Windows.sln
build:
  project: OpenHAB.Windows.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '**/*.appx'
