name: 'CI Build'

env:
  BUILD_NUMBER: '1970.1.1'
  BuildDirectory: '${{github.workspace}}\build'

on: [push, pull_request]

jobs:
  build:
    name: 'Build openHAB Windows App'
    runs-on: windows-latest

    steps:
    - name: Checkout main code
      uses: actions/checkout@v2
      with:
        path: src
        clean: true

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 'latest'
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{runner.os}}-sonar
        restore-keys: ${{runner.os}}-sonar

    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{runner.os}}-sonar-scanner-msbuild
        restore-keys: ${{runner.os}}-sonar-scanner-msbuild

    # - name: Install SonarCloud scanner
    #   if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
    #   shell: powershell
    #   run: |
    #     $directory = New-Item -Path .\.sonar\scanner -ItemType Directory
    #     # dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    #     $file = Join-Path $directory.FullName "sonar-scanner.zip"
    #     Invoke-WebRequest -Uri "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/5.0.4.24009/sonar-scanner-msbuild-5.0.4.24009-net46.zip" -OutFile $file
    #     Expand-Archive -LiteralPath $file -DestinationPath "$($directory.FullName)"

    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    - name: Begin SonarQube analyze
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKE }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"openhab_openhab-windows" /o:"openhab" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.projectBaseDir="${{github.workspace}}\src\"

    - name: Build App
      id: create_app_package
      uses: ./src/.github/workflows/actions/app-build
      with:
        build_configuration: 'Debug'
        output_directory: '${{env.BuildDirectory}}'
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
    
    - name: End SonarQube analyze
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      shell: powershell
      run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{secrets.SONAR_TOKEN}}"